### ISSUE TITLE
phi-replace: Whole Word / Regex?

### ISSUE THREAD

**Issue by hrehfeld** [zk-phi/phi-search#35] opened 2015-02-19 15:10 UTC
Maybe I'm missing something, but phi-replace behaves in a really unexpected way for me:

- it replaces whole words, e.g. in the text "illumination sentence" when I use "illu" as the search string and "foo" as replacement, the result is "foo sentence"
- it uses regex, e.g. I have to use "\." as the search string when trying to match .

are these bugs or expected behavior? (Some documentation would really be awesome)
How do I replace substrings only?

**Comment by zk-phi** [comment] 2015-02-19 15:50
> it replaces whole words, e.g. in the text "illumination sentence" when I use "illu" as the search string
> and "foo" as replacement, the result is "foo sentence"

hmm, I couldn't reproduce on my emacs.

> it uses regex, e.g. I have to use "." as the search string when trying to match .

it's the expected behavior. you need to escape "." like "\.".

**Comment by hrehfeld** [comment] 2015-02-19 20:06
For some reason, it was broken when emacs was restoring the desktop. I deleted my desktop, now it seems to work...

Any ideas what might cause this, or what I can look for in my desktop file?

**Comment by zk-phi** [comment] 2015-02-20 08:06
match data stored at line 143 (`looking-at`) seems broken at line 153 (`replace-match`).
can you try this one ? https://gist.github.com/zk-phi/0b51e6dd665027b1f2df

**Comment by zk-phi** [comment] 2015-03-09 09:12
maybe fixed in the last commit (bd94481)

**Closed by zk-phi** 2015-03-09 09:12 UTC
