### ISSUE TITLE
phi-replace--complete-function: Args out of range: 0, 2

### ISSUE THREAD

**Issue by RasmusWL** [zk-phi/phi-search#32] opened 2015-01-16 10:21 UTC
Just testing out this thing, on my `init.el` which you can find here: https://gist.github.com/RasmusWL/9e6514bed8020753a773 (I'm using emacs 24.3.1, phi-search 20150114.929)

If you put your cursor at the end of the file, replace `search` with `...`, alternate between `y` and `n`, starting with `y`. On the second `y`, I get the error: `phi-replace--complete-function: Args out of range: 0, 2`

Are you able to reproduce these results?

**Comment by zk-phi** [comment] 2015-01-16 17:06
thanks for reporting.

hmm, I couldn't reproduce with vanilla emacs 24.3 on my windows.

![r](https://cloud.githubusercontent.com/assets/3530521/5780264/8b42297a-9dec-11e4-80f5-d8572ec623ba.gif)
(am I doing right?)

can you show me the `*Backtrace*` buffer after the error ?

**Comment by RasmusWL** [comment] 2015-01-22 12:54
It looks right. I had a bit of trouble reproducing as well. But today I found the error again (after realising I should use `M-x toggle-debug-on-error`)


```
Debugger entered--Lisp error: (args-out-of-range 0 2)
  replace-match("...")
  phi-replace--complete-function()
  apply(phi-replace--complete-function nil)
  phi-search-complete()
  phi-replace-again-or-complete()
  ad-Orig-call-interactively(phi-replace-again-or-complete nil nil)
  (with-no-warnings (ad-Orig-call-interactively function record-flag keys))
  (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys)))
  (let ((ido-ubiquitous-next-override (ido-ubiquitous-get-command-override function))) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys))))
  (ido-ubiquitous-with-override (ido-ubiquitous-get-command-override function) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys))))
  (let (ad-return-value) (ido-ubiquitous-with-override (ido-ubiquitous-get-command-override function) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys)))) ad-return-value)
  call-interactively(phi-replace-again-or-complete nil nil)
  read-from-minibuffer("phi-replace: " nil (keymap (3 keymap (3 . phi-search-unlimit)) (13 . phi-search-complete) (remap keymap (phi-search-complete . phi-replace-again-or-complete) (phi-rectangle-kill-region . phi-search-yank-word) (kill-region . phi-search-yank-word) (recenter . phi-search-recenter) (scroll-down-command . phi-search-scroll-down) (pager-page-up . phi-search-scroll-down) (scroll-up-command . phi-search-scroll-up) (pager-page-down . phi-search-scroll-up) (scroll-up . phi-search-scroll-up) (keyboard-quit . phi-search-abort) (phi-search-backward . phi-search-again-or-previous) (phi-search . phi-search-again-or-next)) (18 . phi-search-again-or-previous) (19 . phi-search-again-or-next)))
  phi-search--initialize((" *phi-replace*" (:eval (format " [ %d ]" (length phi-search--overlays)))) (([remap phi-search-complete] quote phi-replace-again-or-complete)) nil nil phi-replace--complete-function nil #[nil "\300\301!\207" [run-hooks phi-replace-init-hook] 2] "phi-replace: ")
  phi-replace--initialize(t)
  phi-replace-query()
  ad-Orig-call-interactively(phi-replace-query record nil)
  (with-no-warnings (ad-Orig-call-interactively function record-flag keys))
  (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys)))
  (let ((ido-ubiquitous-next-override (ido-ubiquitous-get-command-override function))) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys))))
  (ido-ubiquitous-with-override (ido-ubiquitous-get-command-override function) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys))))
  (let (ad-return-value) (ido-ubiquitous-with-override (ido-ubiquitous-get-command-override function) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys)))) ad-return-value)
  call-interactively(phi-replace-query record nil)
  command-execute(phi-replace-query record)
  execute-extended-command(nil "phi-replace-query")
  smex-read-and-run(("toggle-debug-on-error" "debug" "phi-replace-query" "debugger-continue" "auto-fill-mode" "mc/mark-more-like-this-extended" "package-list-packages" "debugger-step-through" "package-install" "forward-same-syntax" "font-lock-fontify-buffer" "ghc-debug" "company-mode" "flycheck-mode" "company-complete" "load-theme" "backward-kill-word" "load-file" "backward-word" "latex-math-mode" "backward-kill-sentence" "my-delete-backward-to-ws" "edebug-defun" "forward-word" "subword-mode" "LaTeX-math-mode" "kill-word" "LaTeX-mode" "fixmee-mode" "winner-undo" "ghc-show-info" "just-one-space" "kill-whitespace" "scroll-bar-mode" "whitespace-mode" "what-cursor-position" "cua-set-rectangle-mark" "byte-recompile-directory" "shell" "fixmee" "TeX-mode" "tabbar-mode" "zap-to-char" "flymake-mode" "flyspell-word" "tex-fold-mode" "make-directory" "replace-regexp" "auto-revert-mode" "transient-mark-mode" ...))
  smex()
  ad-Orig-call-interactively(smex nil nil)
  (with-no-warnings (ad-Orig-call-interactively function record-flag keys))
  (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys)))
  (let ((ido-ubiquitous-next-override (ido-ubiquitous-get-command-override function))) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys))))
  (ido-ubiquitous-with-override (ido-ubiquitous-get-command-override function) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys))))
  (let (ad-return-value) (ido-ubiquitous-with-override (ido-ubiquitous-get-command-override function) (setq ad-return-value (with-no-warnings (ad-Orig-call-interactively function record-flag keys)))) ad-return-value)
  call-interactively(smex nil nil)
```

**Comment by zk-phi** [comment] 2015-01-22 13:46
it seems that the match data is broken when `phi-replace-complete-function` calls `replace-match`.
can you try this one ? (redefine `phi-replace--complete-function` with `C-x C-e`)

https://gist.github.com/zk-phi/66c5bf8689ff6af38a08

if this fixes the problem, i'll commit. thanks.

**Comment by RasmusWL** [comment] 2015-01-22 22:40
Sorry, going on a skiing holiday now. Will test when I get back :)

**Comment by zk-phi** [comment] 2015-04-11 17:21
(just a reminder)

**Comment by RasmusWL** [comment] 2015-04-15 08:18
Sorry about the long wait.

I can't reproduce this any longer (just upgraded to through melpa to 20150408.538)

**Comment by zk-phi** [comment] 2015-04-15 08:33
Thanks for reply. That's great, I'll close this issue.

**Closed by zk-phi** 2015-04-15 08:33 UTC
